apiVersion: apps/v1
kind: Deployment

metadata:
  name: web
  
spec:
  replicas: 1
  selector:
    matchLabels:
      componente: web

  template:
    metadata:
      labels:
        componente: web
    spec:
      containers:
        - name: front-web
          image: aimarsg/as-laboratorio8-web
          ports:
            - containerPort: 5000
